#######
# Compiled from data/group_works/functions/botti_funcs.mcscript
# to .//data/group_works/functions/botti_func/botti_level_2.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# this file is generated based on a function specified in.//data/group_works/functions/botti_funcs.mcscript
title @s times 0 2 0
title @s title [{"text":"あぁ、やばいかもなぁ","color":"dark_blue"}]
effect give @s wither 1 1 true
effect give @s haste 2 2 true
effect give @s slowness 2 2 true
effect give @s hunger 2 2 true