#######
# Compiled from data/group_works/functions/botti_funcs.mcscript
# to .//data/group_works/functions/botti_func/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a at @s if entity @p[distance=10..15] run function group_works:botti_func/botti_level_1
execute as @a at @s if entity @p[distance=15..] run function group_works:botti_func/botti_level_2