#######
# Compiled from data/group_works/functions/load.mcscript
# to .//data/group_works/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function group_works:mcscript/load
