#######
# Compiled from data/group_works/functions/main.mcscript
# to .//data/group_works/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a at @s run function group_works:botti_func/main